cc_library (
  name = 'base',
  srcs = [
    'dist.cc',
    'dtoa.cc',
    'flags.cc',
    'log.cc',
    'registerer.cc',
    'simple_line_reader.cc',
    'string_util.cc',
    'util.cc',
  ],
  deps = ['#pthread']
)
