# cc_binary (
#   name = 'el',
#   srcs = [
#     'reactor/accept_handler.cc',
#     'reactor/connect_handler.cc',
#     'event_main.cc',
#     'reactor/epoll.cc'
#   ],
#   deps = [
#     '//common:base',
#   ],
# )

# cc_binary (
#   name = 'test_net_client',
#   srcs = [
#     'test_net_client.cc',
#     'epoll.cc',
#     'event_loop.cc',
#     'net.cc'
#   ],
#   deps = [
#     '//common:base'
#   ],
# )
